services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asistencia_app
    ports:
      - "8002:8000"
      - "5192:5192"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=asistenciaugel
      - DB_USERNAME=sail
      - DB_PASSWORD=password
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asistencia_network

  db:
    image: postgres:15
    container_name: asistencia_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: asistenciaugel
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sail -d asistenciaugel"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - asistencia_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: asistencia_pgadmin
    restart: unless-stopped
    ports:
      - "5053:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asistencia_network

networks:
  asistencia_network:
    driver: bridge

volumes:
  db-data:
